### ISSUE TITLE
Update logbook

### ISSUE THREAD

**Issue by dazrave** [dazrave/CascadeHA#6]
Add/remove required devices

```
logbook:
  exclude:
    entities:
      - group.internalpir
      - group.groundfloorpir
      - group.firstfloorpir
      - group.externalpir
      - group.reedswitches
      - light.kitchen_left
      - light.kitchen_right
    domains:
      - automation
```
